spring:
  application:
    name: wlcp-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
   port: 443
   ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/wlcp.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-alias: ${SSL_KEYSTORE_ALIAS}
    enabled: true
eureka:
   client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}