spring:
  application:
    name: wlcp-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
   port: 8050
eureka:
   client:
    serviceUrl:
      defaultZone: http://wlcp-discovery-dev:8761/eureka/
